#+title:Evaluation des Performances et Modelisation Librairies Cryptographiques pour les Communications MPI
#+author:Sholde
#+date:2021

* Variables de test

  Utilisation de 4 librairies de cryptographie :

  - OpenSSL
  - BoringSSL
  - Libsodium
  - CryptoPP

  Utilisation de 2 différent système de réseaux :
  
  - Ethernet
  - InfiniBand

* Introduction

  Aujourd'hui les cloud utilisent des appliction du HPC avec MPI et
  ont besoin d'assuré la vie privé et l'intégrité des informations. Le
  fait de sécurisé la librairie MPI est donc un bon choix mais
  différentes failles ont été trouvé dans les premières versions.

  De plus pour accélerer les chiffrements et déchiffrements les
  construceurs de processeurs ont intégré des instructions dans le
  CPU.

  Les librairies cryptographiques modernes utilisent les librairies
  cité ci-dessus qui ont été validé dans un standart.

  Le but est de tester les 4 librairies cryptographiques sur 2 types de
  réseaux différent sur les communications MPI.

  Pour obtenir des gains théorique nous allons séparé les
  communication point à point MPI en 2 paramètres :
  
  - une unique communication point à point comme un test de Ping-Pong
  - de multiple communications en concurence

  Avec notre modèle très simple de communication point à point MPI
  nous allons nous interresser aux performance ainsi qu'u éventuelle
  technique d'optimization pour amèliorer ces performances.

* Travail en relation
** Systèmes antérieurs à la cryptographie *MPI*
   
   Il exeiste des systèmes qui ont les deux problèmes de vulnaribilité
   suivant :
   - la vie privée
   - intégrité des donnée

*** Vie privée

    La vie privé est le but principale du projet, mais est impartaite
    dû à l'insécurité ou l'abus des algorithmes cryptographiques. Par
    exemple le fait ce créer une librairie *MPI* avec un schéma de
    chiffrement simple comme *ECB*.

*** Intégrité

    Différentes options ont été proposés.
    Le premier choix pour sécurisé l'intégrité des messages serait
    d'ajuter une signature mais les schéma de signature digitales
    actuelles coûtent trop cher.
    Le deuxième serait de faire un *checksum* sur tout les messages
    mais il faudrai utilisé un schéma plus compliqué qu'un simple
    schéma de chiffrement par block en chaîne.
    Une dernière option était de chiffrer les données avec un mode
    *ECB* mais cela n'apporte pas l'intégrité du message.

*** A noté

    Ces insécurités ne sont pas présentes dans la litératur. Néanmoins
    les communication MPI ont besoin d'assurer la vie privée et
    l'intégrité des messages.

    De plus les instructions cryptographiques proposé par les
    différent constructeurs de CPU deviennet omniprésent et les
    librairies cryptographiques les utilisent de plus en plus.

** Modélisation des performances

   Les modèles de performances les plus notables :
   - Hockney model
   - LogP model
   - LogGP model
   - PLogP model

   Nous allons montré par la suite que le modèle de *Hockney* peut
   être utilisé pour les paramètres Ping Pong chiffré.

   Les communicatoion chiffré peuvent être vu comme des simples
   communications MPI sur un canal authentifié et/ou privée.

* Contexte
** Schéma de chiffrement
*** Une vue à vole d'oiseau du chiffrement

    Un schéma symétrique de chiffrement est divisé en 3 phase :
    - la génération de la clé
    - le chiffrement
    - le déchiffrement

    A chaque fois que l'on veut chiffrer un message on a besoin du
    message et de la clé, ainsi que pour déchiffrer, on dit que c'est
    un schéma symétrique car la même clé permet de chiffrer et de
    déchiffrer.

    Il y a différent type de schéma au sein des chiffrements
    symétriques comme le chiffrement par blocks. Mais tous les schéma
    symétriques n'ont pas le même taux de sécurité. Par exemple le
    chiffrement pas block tel *ECB* n'est pas sécurisé.

    Il y a d'autres paramètres comme l'intégrité et la performances,
    pour toutes ces raisons nous avons choisis le schéma CGM qui
    propose la vie privée et l'intégrité des messages, la performances
    ainsi d'avoir l'avantage de n'avoir aucune connaissance techniques
    pour comprendre notre travail.

*** Aperçu de GCM
    
    Nous allons utilisé le chiffrement par block AES, avec 2
    différentes tailles de clé : 128 et 256 bits, respectivement pour
    la performance et la sécurité.

    De plus dans l'algoritmhe AES le message chiffré à 28 octets de
    plus que le message clair dû à l'algorithme qui utilise un
    compteur pour identifier les messages.

** Librairies Cryptographiques

   Nos 4 librairies cryptographiques sont publiques et beaucoup
   utilisé.

   *OpenSSL* étant la plus populaire, de nombreuses vulnaribilité ont
   été trouvé. Mais elle implémente les protocoles *TLS* et *SSL*.

   *BoringSSL* est un fork de OpenSSL par *Google* pour leurs produits
   tel que : Chrome/Chromium et Android.

   *Libsodium* a pour objectif la sécurité et la facilité
   d'utilisation. Son avantage est sa portabilité.

   *CryptoPP* est une librairie cryptographique pour le language *C++*
    adopté par *Microsoft* et *Steam*.

* MPI avec des communications chiffré

  Nous avons implémenté une librairie MPI avec des communications
  chiffré avec AES-GCM pour nos 2 tailles de clés et nos 4 librairies.

  Les clés sont en clair dans le code sources pour le moment car le
  but est de testé les performances des librairies cryptographiques
  MPI.

  Pour notre algorithme, il est très simple à comprendre car nous
  n'abordons pas les subtilités bas niveaux.

* Experience

  Nous allons évalué les perfomances de chaque librairies pour
  laquelle utilisé avec les communications *MPI*.

** Equipement du système

   - CPU: Intel Xeon E5-2620 v4 2.10 GHz
   - Memoire: DDR4 RAM 64 GB
   - OS: CentOS 7.6
   - Réseaux: 
     - Ethernet (Intel 82599ES SFI/SFP+)
     - InfiniBand GDR one (Mellanox MT25408A0-FCC-QI ConnectX)
   - Compilation:
     - MPICH
     - MVAPICH
     - Niveau d'optimisation: -O2

** Analyse comparatives

   - *Chiffrement-Déchiffrement:* étude de performance de 500 000
     chiffrement et déchiffrement
   - *Ping-Pong:* mesure de performance des communications bloquantes et
     suivant la taille du message :
     - 1 B < taille < 1 MB : envoie 10 000 fois
     - 1 MB < taille < 2 MB : envoie 1 000 fois
   - *OSU micro-analyse:* mesuere de performance des communications non
     bloquantes. Envoie 64 message par itération pour 100 itération et
     attends une réponse à chaque itération.
   - *Analyse des NAS parralèles:* mesure des performance de chiffrement
     avec MPI dans des applications en utilisant une taille de *Class
     C* pour :
     - BT, CG, FT, IS, MG et SP
