#+title:Evaluation des Performances et Modelisation Librairies Cryptographiques pour les Communications MPI
#+author:Sholde
#+date:2021

* Variables de test

  Utilisation de 4 librairies de cryptographie :

  - OpenSSL
  - BoringSSL
  - Libsodium
  - CryptoPP

  Utilisation de 2 différent système de réseaux :
  
  - Ethernet
  - InfiniBand

* Introduction

  Aujourd'hui les cloud utilisent des appliction du HPC avec MPI et
  ont besoin d'assuré la vie privé et l'intégrité des informations. Le
  fait de sécurisé la librairie MPI est donc un bon choix mais
  différentes failles ont été trouvé dans les premières versions.

  De plus pour accélerer les chiffrements et déchiffrements les
  construceurs de processeurs ont intégré des instructions dans le
  CPU.

  Les librairies cryptographiques modernes utilisent les librairies
  cité ci-dessus qui ont été validé dans un standart.

  Le but est de testé les 4 librairies cryptographiques sur 2 types de
  réseaux différent sur les communications MPI.

  Pour obtenir des gains théorique nous allons séparé les
  communication point à point MPI en 2 paramètres :
  
  - une unique communication point à point comme un test de Ping-Pong
  - de multiple communications en concurence

  Avec notre modèle très simple de communication point à point MPI
  nous allons nous interresser aux performance ainsi qu'u éventuelle
  technique d'optimization pour amèliorer ces performances.

* Travail en relation
** Systèmes antérieurs à la cryptographie *MPI*
   
   Il exeiste des systèmes qui ont les deux problèmes de vulnaribilité
   suivant :
   - la vie privée
   - intégrité des donnée

*** Vie privée

    La vie privé est le but principale du projet, mais est impartaite
    dû à l'insécurité ou l'abus des algorithmes cryptographiques. Par
    exemple le fait ce créer une librairie *MPI* avec un schéma de
    chiffrement simple comme *ECB*.

*** Intégrité

    Différentes options ont été proposés.
    Le premier choix pour sécurisé l'intégrité des messages serait
    d'ajuter une signature mais les schéma de signature digitales
    actuelles coûtent trop cher.
    Le deuxième serait de faire un *checksum* sur tout les messages
    mais il faudrai utilisé un schéma plus compliqué qu'un simple
    schéma de chiffrement par block en chaîne.
    Une dernière option était de chiffrer les données avec un mode
    *ECB* mais cela n'apporte pas l'intégrité du message.

*** A noté

    Ces insécurités ne sont pas présentes dans la litératur. Néanmoins
    les communication MPI ont besoin d'assurer la vie privée et
    l'intégrité des messages.

    De plus les instructions cryptographiques proposé par les
    différent constructeurs de CPU deviennet omniprésent et les
    librairies cryptographiques les utilisent de plus en plus.

** Modélisation des performances

   Les modèles de performances les plus notables :
   - Hockney model
   - LogP model
   - LogGP model
   - PLogP model

   Nous allons montré par la suite que le modèle de *Hockney* peut
   être utilisé pour les paramètres Ping Pong chiffré.

   Les communicatoion chiffré peuvent être vu comme des simples
   communications MPI sur un canal authentifié et/ou privée.

* Contexte
** Schéma de chiffrement
*** Une vue à vole d'oiseau du chiffrement

    Un schéma symétrique de chiffrement est divisé en 3 phase :
    - la génération de la clé
    - le chiffrement
    - le déchiffrement

    A chaque fois que l'on veut chiffrer un message on a besoin du
    message et de la clé, ainsi que pour déchiffrer, on dit que c'est
    un schéma symétrique car la même clé permet de chiffrer et de
    déchiffrer.

    Il y a différent type de schéma au sein des chiffrements
    symétriques comme le chiffrement par blocks. Mais tous les schéma
    symétriques n'ont pas le même taux de sécurité. Par exemple le
    chiffrement pas block tel *ECB* n'est pas sécurisé.

    Il y a d'autres paramètres comme l'intégrité et la performances,
    pour toutes ces raisons nous avons choisis le schéma CGM qui
    propose la vie privée et l'intégrité des messages, la performances
    ainsi d'avoir l'avantage de n'avoir aucune connaissance techniques
    pour comprendre notre travail.

*** Aperçu de GCM
** Librairies Cryptographiques
